# Generated by Django 6.0.4 on 2026-04-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='page',
            field=models.CharField(blank=True, choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Services'), ('disclaimer', 'Disclaimer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='core.tool'),
        ),
    ]
