# Generated by Django 6.0.4 on 2026-04-22 11:26

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={},
        ),
        migrations.AddField(
            model_name='tool',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
