# Generated by Django 6.0.4 on 2026-04-19 09:45

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260418_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ব্লগের শিরোনাম')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('content', django_summernote.fields.SummernoteTextField(verbose_name='ব্লগের কনটেন্ট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='প্রকাশ করা হবে?')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name']},
        ),
    ]
