# Generated by Django 6.0.4 on 2026-04-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tool_options_tool_content_tool_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
