# Generated by Django 6.0.4 on 2026-04-28 09:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tool_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
